### ISSUE TITLE
6S main.f returns error

### ISSUE THREAD

**Issue by soypat** [Konstantin8105/f4go#39]
[Main 6S fortran](https://github.com/jgomezdans/sixs/tree/master/sixs) file returns error. Also would be nice if there was an -all flag to transliterate all .f files in current directory.

**Comment by Konstantin8105** [comment]
Hello,
Try `f4go *.f` in folder `sixs` for transpiling many files.
Yes, not everything are implemented, now.
Feel free for help to project:
* adding detail of error
* creating PR

**Comment by soypat** [comment]
Alright! I'm new to this whole issues thing, what does PR mean?

**Comment by Konstantin8105** [comment]
PR is pull request. See https://github.com/Konstantin8105/f4go/pulls
If you create a patch for creating that project better, then you can inject your code to the project.
More details https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by soypat** [comment]
closing due to age
