### ISSUE TITLE
f4go fails to transpile PYTHIA

### ISSUE THREAD

**Issue by sbinet** [Konstantin8105/f4go#6]
I tried to transpile a CERN-based FORTRAN77 code used to simulate high energy physics processes:
- http://home.thep.lu.se/~torbjorn/pythia6/pythia6428.f

but the transpilation processes failed.
here are a couple of the error messages:

```
$> curl -O -L http://home.thep.lu.se/~torbjorn/pythia6/pythia6428.f
$> f4go ./pythia6428.f
[...]
pythia6428.f : Parsing error : Cannot identify token in left part separation :, in MIN ( 1e0 , MAX ( PARJ ( 129 ) , ( 2e0 * PARU ( 112 ) / ECM ) ** 2 ) )

[...]
pythia6428.f : Parsing error : Recover parseStmt pos{{54565 7}}: Not acceptable type : X ( 1 )
[...]
```

some of these errors may come from the use of `IMPLICIT`, though.

**Comment by Konstantin8105** [comment]
Hello, @sbinet 
I am glad to see you on my project. Thank you for gonum work.
The biggest problem of that project is creating AST tree for FORTRAN source, so I create a workaround for avoid that work, but as you see - it is not have full implementation of FORTRAN-language specification.
Thank you for you feedback, I will try to solve that task on next week, but without garantee.

**Comment by Konstantin8105** [comment]
As I see - also problem with `COMMON` and in `DATA` for matrixes.
